### get_all_assignments
POST http://localhost:8080/local/servers/main.php HTTP/1.1
Content-Type: application/json
api-token: 5a1a68407745899d3c286ee41113a957

{
  "action": "get_all_assignments"
}


### create_new_assignment
POST http://localhost:8080/local/servers/main.php HTTP/1.1
Content-Type: application/json
api-token: 5a1a68407745899d3c286ee41113a957

{
  "action": "create_new_course",
  "data": {
    "fullname": "OPP0",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn-zRLDUWhTLpBICQiT4gRJuqsGnAIwnrj8Q&s",
    "shortname": "OP0P-113-2026",
    "category": 1,
    "startdate": "2026-02-02",
    "enddate": "2026-05-02",
    "idnumber": "o0pp-112-2026",
    "summary": "# Assignment for JavaScript"
  }
}


### create_new_assignment
POST http://localhost:8080/local/servers/main.php HTTP/1.1
Content-Type: application/json
authorization: 5a1a68407745899d3c286ee41113a957

{
  "action": "create_new_assignment",
  "data": {
    "course": "2",
    "name": "Assignment 1",
    "intro": "0",
    "activity": "0",
    "allowsubmissionsfromdate": "0",
    "duedate": "0",
    "cutoffdate": "0",
    "gradingduedate": "0"
  }
}