
### get token user
POST http://localhost:8080/local/servers/main.php HTTP/1.1
Content-Type: application/json
api-token: 342fd2f65d6bb542079e046056251e20

{
    "action": "get_user"
}

### get token course
POST http://localhost:8080/local/servers/main.php HTTP/1.1
Content-Type: application/json
api-token: 342fd2f65d6bb542079e046056251e20

{
  "action": "create_user",
  "data": {
    "firstname": "Addy Esteban",
    "lastname": "Jaime Cordero",
    "username": "addyjaime",
    "email": "addyjaime@gmail.com",
    "password": "Alicia01$",
    "idnumber": "00000000000",
    "phone": "646-389-2132",
    "country": "DO",
    "lang": "en"
  }
}